src/Entity/Booking.php
<?php

namespace App\Entity;

use App\Repository\BookingRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\DBAL\Types\Types;
use Doctrine\ORM\Mapping as ORM;
use Symfony\Component\Serializer\Annotation\Groups;

#[ORM\Entity(repositoryClass: BookingRepository::class)]
class Booking
{
    #[ORM\Id]
    #[ORM\GeneratedValue]
    #[ORM\Column]
    #[Groups('classicalUser')]
    private ?int $id = null;

    #[ORM\Column(type: Types::SMALLINT)]
    #[Groups('classicalUser')]
    private ?int $state = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Groups('classicalUser')]
    private ?\DateTimeInterface $created_date = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE, nullable: true)]
    #[Groups('classicalUser')]
    private ?\DateTimeInterface $updated_date = null;

    #[ORM\ManyToOne(inversedBy: 'bookings')]
    private ?User $user;

    #[ORM\ManyToOne(inversedBy: 'bookings')]
    #[ORM\JoinColumn(nullable: false)]
    private ?Office $office = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Groups('classicalUser')]
    private ?\DateTimeInterface $start_date = null;

    #[ORM\Column(type: Types::DATETIME_MUTABLE)]
    #[Groups('classicalUser')]
    private ?\DateTimeInterface $end_date = null;

    #[ORM\Column(nullable: true)]
    private ?int $capacity = null;

    public function __construct()
    {
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getState(): ?int
    {
        return $this->state;
    }

    public function setState(int $state): self
    {
        $this->state = $state;

        return $this;
    }

    public function getCreatedDate(): ?\DateTimeInterface
    {
        return $this->created_date;
    }

    public function setCreatedDate(\DateTimeInterface $created_date): self
    {
        $this->created_date = $created_date;

        return $this;
    }

    public function getUpdatedDate(): ?\DateTimeInterface
    {
        return $this->updated_date;
    }

    public function setUpdatedDate(?\DateTimeInterface $updated_date): self
    {
        $this->updated_date = $updated_date;

        return $this;
    }

    public function getUser(): ?User
    {
        return $this->user;
    }

    public function setUser(?User $user): self
    {
        $this->user = $user;

        return $this;
    }

    public function getOffice(): ?Office
    {
        return $this->office;
    }

    public function setOffice(?Office $office): self
    {
        $this->office = $office;

        return $this;
    }

    public function getStartDate(): ?\DateTimeInterface
    {
        return $this->start_date;
    }

    public function setStartDate(\DateTimeInterface $start_date): self
    {
        $this->start_date = $start_date;

        return $this;
    }

    public function getEndDate(): ?\DateTimeInterface
    {
        return $this->end_date;
    }

    public function setEndDate(\DateTimeInterface $end_date): self
    {
        $this->end_date = $end_date;

        return $this;
    }

    public function getCapacity(): ?int
    {
        return $this->capacity;
    }

    public function setCapacity(?int $capacity): self
    {
        $this->capacity = $capacity;

        return $this;
    }

}

src/Form/BookingType.php
<?php

namespace App\Form;

use App\Entity\Booking;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class BookingType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('start_date')
            ->add('end_date')
            ->add('capacity')
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Booking::class,
        ]);
    }
}

src/Controller/BookingController.php
<?php

namespace App\Controller;

use App\Entity\Booking;
use App\Entity\Office;
use App\Form\BookingType;
use App\Repository\BookingRepository;
use App\Repository\OfficeRepository;
use App\Repository\UserRepository;
use App\Service\AppSerializer;
use DateTime;
use App\Service\PdfService;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\JsonResponse;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

use Symfony\Component\Security\Core\Security;

#[Route('/booking')]
class BookingController extends AbstractController
{
    private AppSerializer $appSerializer;

    public function __construct()
    {
        $this->appSerializer = new AppSerializer();
    }

    #[Route('/', name: 'app_booking_index', methods: ['GET'])]
    public function index(BookingRepository $bookingRepository): Response
    {
        return $this->render('booking/index.html.twig', [
            'bookings' => $bookingRepository->findAll(),
        ]);
    }

    #[Route('/new', name: 'app_booking_new', methods: ['GET', 'POST'])]
    public function new(Request $request, BookingRepository $bookingRepository, OfficeRepository $officeRepository, Security $security): Response
    {
        $booking = new Booking();
        $form = $this->createForm(BookingType::class, $booking);

        

        if (!empty($request->getContent())) {
            $startDate = $request->get('start_date');
            $endDate = $request->get('end_date');
            $capacity = $request->get('capacity');
            $officeId = $request->get('office');
            $user = $security->getUser();
                
            if (!empty($officeId)) {
                $office = $officeRepository->findOneBy(["id" => $officeId]);

                if (!empty($startDate) && !empty($endDate) && !empty($capacity) && !empty($office) && !empty($user)) {

                    $booking->setStartDate(new DateTime(date('Y-m-d H:i:s',$startDate)))
                    ->setEndDate(new DateTime(date('Y-m-d H:i:s',$endDate)))
                    ->setCapacity($capacity)
                    ->setState(3)
                    ->setCreatedDate(new DateTime())
                    ->setOffice($office)
                    ->setUser($user);
    
                    $bookingRepository->save($booking, true);
    
                    return $this->redirectToRoute('app_home');
                } 
            }
            
            if(!empty($officeId)) {
                return $this->redirectToRoute('app_office_show',  array('id' => $officeId));
            } else {
                return $this->redirectToRoute('app_home');
            }
           
        }


        $form->handleRequest($request);
        
        if ($form->isSubmitted() && $form->isValid()) {
            $bookingRepository->save($booking, true);

            return $this->redirectToRoute('app_booking_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('booking/new.html.twig', [
            'booking' => $booking,
            'form' => $form,
        ]);
    }

    #[Route('/{id}', name: 'app_booking_show', methods: ['GET'])]
    public function show(Booking $booking): Response
    {
        return $this->render('booking/show.html.twig', [
            'booking' => $booking,
        ]);
    }

    #[Route('/cancel/{id}', name: 'app_booking_cancel', methods: ['GET'])]
    public function cancelReservation(Booking $booking, BookingRepository $bookingRepository): Response
    {
        if (!empty($booking)) {
            $booking->setState(4);
            $bookingRepository->save($booking, true);
        }

        return $this->redirect('/user/profile');
    }

    #[Route('/{id}/edit', name: 'app_booking_edit', methods: ['GET', 'POST'])]
    public function edit(Request $request, Booking $booking, BookingRepository $bookingRepository): Response
    {
        $form = $this->createForm(BookingType::class, $booking);
        $form->handleRequest($request);

        if ($form->isSubmitted() && $form->isValid()) {
            $bookingRepository->save($booking, true);

            return $this->redirectToRoute('app_booking_index', [], Response::HTTP_SEE_OTHER);
        }

        return $this->renderForm('booking/edit.html.twig', [
            'booking' => $booking,
            'form' => $form,
        ]);
    }

    #[Route('/delete/{id}', name: 'app_booking_delete', methods: ['GET','POST'])]
    public function delete(Request $request, Booking $booking, BookingRepository $bookingRepository): Response
    {        
        if ($this->isCsrfTokenValid('delete'.$booking->getId(), $request->request->get('_token'))) {
            $bookingRepository->remove($booking, true);
        }

        return $this->redirectToRoute('app_booking_index', [], Response::HTTP_SEE_OTHER);
    }

    #[Route('/contrat/{id}', name: "app_booking_contrat", methods: ['GET'])]
    public function contratPdf(PdfService $pdf, Request $request, Booking $booking, BookingRepository $bookingRepository) : Response
    {
        $html = $this->renderView('booking/contrat.html.twig', ['booking' => $booking]);
        return $pdf->generateBinaryPDF($html, 'contrat');
    }

    #[Route('/facture/{id}', name:"app_booking_facture", methods: ['GET'])]
    public function facturePdf(PdfService $pdf, Request $request, Booking $booking, BookingRepository $bookingRepository, OfficeRepository $officeRepository, UserRepository $userRepository) : Response
    {
        $office = (object)$officeRepository->findOneBy(['id' => $booking->getOffice()->getId()]);
        $user = $userRepository->findOneBy(['id' => $booking->getUser()->getId()]);
        $html = $this->renderView('booking/facture.html.twig', ['booking' => $booking, 'office' => $office, 'user' => $user]);
        return $pdf->generateBinaryPDF($html, 'facture');
    }
}

templates/booking/_delete_form.html.twig
<form method="post" action="{{ path('app_booking_delete', {'id': booking.id}) }}" onsubmit="return confirm('Are you sure you want to delete this item?');">
    <input type="hidden" name="_token" value="{{ csrf_token('delete' ~ booking.id) }}">
    <button class="btn">Delete</button>
</form>

templates/booking/_form.html.twig
{{ form_start(form) }}
    {{ form_widget(form) }}
    <button class="btn">{{ button_label|default('Save') }}</button>
{{ form_end(form) }}

templates/booking/contrat.html.twig
{% block stylesheets %}
	<style>
		body {
			background: #FFFFFF;
			margin-left: 25px
		}

		#content {
			margin-top: 75px;
		}

		#sitename {
			position: absolute;
			width: 123px;
			height: 21px;
			left: 98px;
			top: 23px;
			font-style: normal;
			font-weight: 700;
			font-size: 14px;
			line-height: 150%;
			letter-spacing: -0.011em;
			color: #FF2768;
		}

		#docTitle {
			position: relative;
			top: 64px;
			font-style: normal;
			font-weight: 800;
			font-size: 16px;
			line-height: 150%;
			text-align: center;
			letter-spacing: -0.011em;
			color: #FF2768;
		}

		#logo {
			position: absolute;
			width: 64px;
			height: 61px;
			right: 0;
			bottom: 1px;
			border-radius: 50px;
		}

		#footer {
			position: absolute;
			bottom: 10px;
			font-style: italic;
			font-weight: 600;
			font-size: 11px;
			line-height: 150%;
			text-align: center;
			letter-spacing: -0.011em;
			color: #BBBBBB;
		}

		.text {
			position: relative;
			font-style: normal;
			font-weight: 400;
			font-size: 12px;
			line-height: 100%;
			letter-spacing: -0.011em;
		}

		.title {
			margin-top: 10px;
			position: relative;
			font-style: normal;
			font-weight: 700;
			font-size: 14px;
			line-height: 100%;
			letter-spacing: -0.011em;
			text-decoration-line: underline;
			color: #FF2768;
		}
	</style>
{% endblock %}

{% block body %}
	<div id="sitename">
		Around the corner
	</div>
	<div id="docTitle">
		Synthèse du contrat de location entre hote et loueur
	</div>
	<div id="content">
		<div class="text">
			Around the corner et l’Hôte sont liés par un contrat de prestations de services régissant l’intendance et les services nécessaires à la location de courte durée du bien. Les deux parties ont acceptés les CGU de Around the corner pour la mise en locationn via la plateforme around the corner.
													
            Les points clés de ce contrat de prestation sont les suivants :
		</div>
		<div class="title">
			Quelles sont les obligations de l’Hôte ?
		</div>
        <div class="text">
            L'Hôte garentit respecter les obligations légales et règlementaires attachées au bien, ainsi qu'avoir
            réalisé les démarches nécessaires en vue de la mise en location de courte durée.
        </div>
        <div class="title">
			Quelles sont les obligations de hote et les services proposés ?
		</div>
        <div class="text">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam id dui non metus suscipit maximus vitae et mauris. Phasellus tincidunt est quis felis ultricies, et aliquam neque faucibus. Nunc vehicula leo vel nisi consequat, ac accumsan ligula tempus. Aenean sollicitudin lorem et augue condimentum sollicitudin at vel sem. Ut quis facilisis nisi. Aliquam vestibulum, est vitae tristique rutrum, ipsum erat pulvinar mauris, ac ultrices ante nulla sed nisl. In hac habitasse platea dictumst. Vestibulum vestibulum dolor diam, nec cursus massa porttitor vitae. 
        </div>
        <div class="title">
			Quel est le tarif ?
		</div>
        <div class="text">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam id dui non metus suscipit maximus vitae et mauris. Phasellus tincidunt est quis felis ultricies, et aliquam neque faucibus. Nunc vehicula leo vel nisi consequat, ac accumsan ligula tempus. Aenean sollicitudin lorem et augue condimentum sollicitudin at vel sem. Ut quis facilisis nisi. Aliquam vestibulum, est vitae tristique rutrum, ipsum erat pulvinar mauris, ac ultrices ante nulla sed nisl. In hac habitasse platea dictumst. Vestibulum vestibulum dolor diam, nec cursus massa porttitor vitae. 
        </div>
        <div class="title">
			Quel est la durée de ce contrat ?
		</div>
        <div class="text">
            Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam id dui non metus suscipit maximus vitae et mauris. Phasellus tincidunt est quis felis ultricies, et aliquam neque faucibus. Nunc vehicula leo vel nisi consequat, ac accumsan ligula tempus. Aenean sollicitudin lorem et augue condimentum sollicitudin at vel sem. Ut quis facilisis nisi. Aliquam vestibulum, est vitae tristique rutrum, ipsum erat pulvinar mauris, ac ultrices ante nulla sed nisl. In hac habitasse platea dictumst. Vestibulum vestibulum dolor diam, nec cursus massa porttitor vitae. 
        </div>
	</div>
{% endblock %}

templates/booking/edit.html.twig
{% extends 'base.html.twig' %}

{% block title %}Edit Booking{% endblock %}

{% block body %}
    <h1>Edit Booking</h1>

    {{ include('booking/_form.html.twig', {'button_label': 'Update'}) }}

    <a href="{{ path('app_booking_index') }}">back to list</a>

    {{ include('booking/_delete_form.html.twig') }}
{% endblock %}

templates/booking/facture.html.twig
{% block stylesheets %}
	<style>
		body {
			background: #FFFFFF;
			margin-left: 25px
		}

		#docTitle {
			position: relative;
			top: 64px;
			font-style: normal;
			font-weight: 800;
			font-size: 16px;
			line-height: 150%;
			text-align: center;
			letter-spacing: -0.011em;
			color: #FF2768;
		}

		#content {
			margin-top: 75px;
		}

		#sitename {
			position: absolute;
			width: 123px;
			height: 21px;
			left: 98px;
			top: 23px;
			font-style: normal;
			font-weight: 700;
			font-size: 14px;
			line-height: 150%;
			letter-spacing: -0.011em;
			color: #FF2768;
		}

		.text {
			position: relative;
			font-style: normal;
			font-weight: 400;
			font-size: 12px;
			line-height: 100%;
			letter-spacing: -0.011em;
		}

		.title {
			margin-top: 10px;
			position: relative;
			font-style: normal;
			font-weight: 700;
			font-size: 14px;
			line-height: 100%;
			letter-spacing: -0.011em;
			text-decoration-line: underline;
			color: #FF2768;
		}
		.card {

			position: relative;
			width: 253px;
            padding: 5px;
			background: #FFFFFF;
            border: 1px solid;
			box-shadow: 0 2px 4px rgba(0, 0, 0, 0.25);
			border-radius: 10px;
		}

		.hr {

			position: absolute;
			width: 190px;
			height: 0;
			left: 93px;
			top: 309px;
			border: 0.5px solid #000000;
		}
	</style>
{% endblock %}
{% block body %}
	<div id="sitename">
		Around the corner
	</div>
	<div id="docTitle">
		Votre reçu de Around the corner
	</div>
	<div id="content">
		<div class="card">
			<div class="title">
				{{ office.name }}
			</div>
			<div class="text">
                À {{ office.city }}, {{ office.adress }}<br>
				Du <b>{{ booking.StartDate | date('d-m-Y') }}</b> au <b>{{ booking.EndDate |date('d-m-Y') }}</b><br>
                Pour <b>{{ booking.capacity }}</b> personnes<br><br>

                À payer : {{ office.price }} € par jours
			</div>
		</div>
	</div>
{% endblock %}

templates/booking/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Booking index{% endblock %}

{% block body %}
    <h1>Booking index</h1>

    <table class="table">
        <thead>
            <tr>
                <th>Id</th>
                <th>State</th>
                <th>Created_date</th>
                <th>Updated_date</th>
                <th>actions</th>
            </tr>
        </thead>
        <tbody>
        {% for booking in bookings %}
            <tr>
                <td>{{ booking.id }}</td>
                <td>{{ booking.state }}</td>
                <td>{{ booking.createdDate ? booking.createdDate|date('Y-m-d H:i:s') : '' }}</td>
                <td>{{ booking.updatedDate ? booking.updatedDate|date('Y-m-d H:i:s') : '' }}</td>
                <td>
                    <a href="{{ path('app_booking_show', {'id': booking.id}) }}">show</a>
                    <a href="{{ path('app_booking_edit', {'id': booking.id}) }}">edit</a>
                </td>
            </tr>
        {% else %}
            <tr>
                <td colspan="5">no records found</td>
            </tr>
        {% endfor %}
        </tbody>
    </table>

    <a href="{{ path('app_booking_new') }}">Create new</a>
{% endblock %}

templates/booking/new.html.twig
{% extends 'base.html.twig' %}

{% block title %}New Booking{% endblock %}

{% block body %}
    <h1>Create new Booking</h1>

    {{ include('booking/_form.html.twig') }}

    <a href="{{ path('app_booking_index') }}">back to list</a>
{% endblock %}

templates/booking/show.html.twig
{% extends 'base.html.twig' %}

{% block title %}Booking{% endblock %}

{% block body %}
    <h1>Booking</h1>

    <table class="table">
        <tbody>
            <tr>
                <th>Id</th>
                <td>{{ booking.id }}</td>
            </tr>
            <tr>
                <th>State</th>
                <td>{{ booking.state }}</td>
            </tr>
            <tr>
                <th>Created_date</th>
                <td>{{ booking.createdDate ? booking.createdDate|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
            <tr>
                <th>Updated_date</th>
                <td>{{ booking.updatedDate ? booking.updatedDate|date('Y-m-d H:i:s') : '' }}</td>
            </tr>
        </tbody>
    </table>

    <a href="{{ path('app_booking_index') }}">back to list</a>

    <a href="{{ path('app_booking_edit', {'id': booking.id}) }}">edit</a>

    {{ include('booking/_delete_form.html.twig') }}
{% endblock %}